version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Ánh xạ cổng 6379 của container Redis vào cổng 6379 của máy chủ
    volumes:
      - redis-data:/data  # Đảm bảo dữ liệu Redis được lưu trữ ngoài container
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge
